image:
  registry: registry.k8s.io
  repository: external-dns/external-dns
  tag: v0.14.0

# restrict to namespace
# namespace: external-dns 

provider: webhook

extraArgs:
  webhook-provider-url: http://localhost:8888
  txt-prefix: external-dns

sidecars:
  - name: external-dns-domeneshop-webhook
    image: dummy:latest
    ports:
      - containerPort: 8888
        name: http
    # livenessProbe:
    #   httpGet:
    #     path: /health
    #     port: http
    #   initialDelaySeconds: 10
    #   timeoutSeconds: 5
    # readinessProbe:
    #   httpGet:
    #     path: /health
    #     port: http
    #   initialDelaySeconds: 10
    #   timeoutSeconds: 5
    env:
      # - name: LOG_LEVEL
      #   value: debug
      - name: TOKEN
        valueFrom:
          secretKeyRef:
            name: external-dns-domeneshop-webhook
            key: TOKEN
      - name: SECRET
        valueFrom:
          secretKeyRef:
            name: external-dns-domeneshop-webhook
            key: SECRET